version: '1.0'

name: 'go-nginx-iot'

services:
  backend:
    build: ./Backend/
    container_name: "Go-Alpine"
    restart: always
    ports: 
      - "8080:8080"
    networks:
      - common_network

  frontend:
    build: ./Frontend/
    container_name: "Nginx-Alpine"
    restart: always
    ports: 
      - "3000:80"
    depends_on:
      - backend
    links:
      - backend
    networks:
      - common_network

networks:
  common_network: 
    driver: bridge